query {
  stopka {
    background {
      id
      url
    }
  	companyDescription
  	companyDescription_eng
    tabs {
      id
      header
      entries {
        id
        entry
      }
    }
    tabs_eng {
      id
      header
      entries {
        id
        entry
      }
    }
  }
}