query {
  stronaGlowna {
    id
    background {
      id
      url
    }
    posts {
      id
      title
      text
    }
    posts_eng {
      id
      title
      text
    }
    body
    body_eng
  }
}